const entries=[
['Command Deck','dashboard','home dashboard command deck start'],['Quick Lookup','quick-ref','fast answer hospital refinery buy weapons components'],['Systems Index','systems','stanton pyro nyx systems'],['Stanton','stanton','arcCorp hurston microtech crusader live system'],['ArcCorp','arccorp','area18 baijini wala lyria'],['Wala','wala','moon arccorp outposts mining cargo surface ops'],['Hurston','hurston','lorville everus harbor aberdeen arial ita magda'],['microTech','microtech','new babbage port tressler calliope clio euterpe'],['Crusader','crusader','orison seraphim daymar yela cellin'],['Pyro','pyro','lawless dangerous survival fuel'],['Nyx','nyx','levski refinery future'],['Disko Fleet','fleet','ships a1 spirit asgard atls c8r cutter dragonfly super hornet golem guardian hermes hull ironclad prowler moth railen reclaimer roc sabre starfarer vulture zeus'],['Cargo Haulers','fleet','hermes hull b hull c ironclad railen prowler utility starfarer gemini'],['Industrial Salvage','fleet','reclaimer vulture moth roc golem ox atls salvage mining'],['Combat Escort','fleet','guardian mx super hornet sabre asgard pittbull dragonfly'],['Medical Rescue','medical','c8r pisces ursa medivac zeus hospital respawn rescue'],['Industry','industry','mining salvage cargo refining trading'],['Combat','combat','bounty escort mercenary weapons loadouts guardian mx ad5b'],['Medical','medical','clinic hospital respawn rescue'],['Patch Log','patch-log','4.8.3 live patch verify changes']
];
const search=document.getElementById('search');const results=document.getElementById('results');
function renderResults(q){q=q.trim().toLowerCase();if(!q){results.style.display='none';results.innerHTML='';return}const hits=entries.filter(e=>(e[0]+' '+e[2]).toLowerCase().includes(q)).slice(0,8);results.innerHTML=hits.length?hits.map(e=>`<a href="#${e[1]}" data-target="${e[1]}"><strong>${e[0]}</strong><br><small>${e[2]}</small></a>`).join(''):`<a href="#patch-log"><strong>No exact hit yet</strong><br><small>Use this as a build note for the next Atlas pass.</small></a>`;results.style.display='block'}
search.addEventListener('input',e=>renderResults(e.target.value));
results.addEventListener('click',e=>{if(e.target.closest('a')){results.style.display='none';search.value=''}});
document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))results.style.display='none'});
const links=[...document.querySelectorAll('.sidebar a')];const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);
const observer=new IntersectionObserver(items=>{items.forEach(item=>{if(item.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+item.target.id))}})},{rootMargin:'-25% 0px -70% 0px'});sections.forEach(s=>observer.observe(s));
const topBtn=document.getElementById('topBtn');window.addEventListener('scroll',()=>{topBtn.style.display=window.scrollY>600?'block':'none'});topBtn.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
