window.ATLAS_FLEET = [
  { name:"A1 Spirit", group:"Combat", role:"Bomber / strike platform", priority:"Strike", checklist:"Bombing runs, fast strike work, and precision pressure.", status:"Active" },
  { name:"Asgard", group:"Combat", role:"Dropship", priority:"Dropship", checklist:"Troop movement, hot insertions, and heavy landing operations.", status:"Active" },
  { name:"ATLS", group:"Utility", role:"Cargo support exosuit", priority:"Utility", checklist:"Move freight, support hangar work, speed up loading.", status:"Support" },
  { name:"Ares Inferno", group:"Combat", role:"Heavy ballistic fighter", priority:"Anti-large", checklist:"Bring the big gun when something large needs regretting its choices.", status:"Active" },
  { name:"Arrow", group:"Combat", role:"Light fighter", priority:"Interceptor", checklist:"Fast response, dogfighting practice, light patrol.", status:"Active" },
  { name:"C8R Pisces", group:"Medical", role:"Medical shuttle", priority:"Rescue", checklist:"Fast medical response, bunker recovery, quick transport.", status:"Ready" },
  { name:"Corsair", group:"Exploration", role:"Armed explorer", priority:"Daily flagship", checklist:"Explore with teeth. Good when the route may get ugly.", status:"Favorite" },
  { name:"Cutter", group:"Utility", role:"Starter utility ship", priority:"Daily", checklist:"Short hops, errands, low-pressure movement.", status:"Ready" },
  { name:"Cutlass Black", group:"Utility", role:"Multi-role workhorse", priority:"Workhorse", checklist:"Bunkers, boxes, light cargo, vehicle hauling, backup fighter.", status:"Ready" },
  { name:"Dragonfly Black", group:"Utility", role:"Grav-lev bike", priority:"Ground", checklist:"Surface scouting and fast local movement.", status:"Support" },
  { name:"F7C-M Super Hornet", group:"Combat", role:"Heavy fighter", priority:"Dogfight", checklist:"Combat patrol and hard-nosed fighting.", status:"Active" },
  { name:"Golem OX", group:"Industry", role:"Industrial support", priority:"Industrial", checklist:"Industrial work lane. Details to verify and expand.", status:"Verify" },
  { name:"Guardian MX", group:"Combat", role:"Heavy fighter", priority:"Favorite", checklist:"Primary combat platform. Loadout page comes first.", status:"Favorite" },
  { name:"Hermes", group:"Cargo", role:"Cargo hauler", priority:"Hauler", checklist:"Cargo hauling lane. Kept under Cargo Haulers.", status:"Active" },
  { name:"Hull B", group:"Cargo", role:"Medium cargo hauler", priority:"Trade", checklist:"Mid-size hauling and trade routes.", status:"Active" },
  { name:"Hull C", group:"Cargo", role:"Large cargo hauler", priority:"Bulk", checklist:"Big freight, station-to-station work, serious hauling.", status:"Active" },
  { name:"Ironclad", group:"Cargo", role:"Heavy cargo / assault transport", priority:"Heavy", checklist:"Large cargo, vehicle transport, high-value runs.", status:"Active" },
  { name:"Moth", group:"Industry", role:"Industrial salvage ship", priority:"Salvage", checklist:"Industrial salvage lane. Kept under salvage.", status:"Verify" },
  { name:"Prowler Utility", group:"Cargo", role:"Cargo hauler", priority:"Utility Cargo", checklist:"Cargo utility lane. Kept under Cargo Haulers.", status:"Active" },
  { name:"PTV", group:"Utility", role:"Ground vehicle", priority:"Ground", checklist:"Hangar fun, local movement, ground support.", status:"Support" },
  { name:"Railen", group:"Cargo", role:"Alien cargo hauler", priority:"Trade", checklist:"Cargo runs with style. Dedicated trade page later.", status:"Active" },
  { name:"Reclaimer", group:"Industry", role:"Heavy salvage", priority:"Crew Salvage", checklist:"Crew salvage operations and large recovery loops.", status:"Active" },
  { name:"ROC", group:"Industry", role:"Ground mining vehicle", priority:"Mining", checklist:"Gem mining, surface operations, vehicle support.", status:"Ready" },
  { name:"Sabre", group:"Combat", role:"Stealth fighter", priority:"Stealth", checklist:"Low-signature combat and patrol.", status:"Active" },
  { name:"Starfarer Gemini", group:"Support", role:"Fuel / military support", priority:"Support", checklist:"Refueling support, fleet operations, heavy logistics.", status:"Support" },
  { name:"Ursa Medivac", group:"Medical", role:"Ground medical rover", priority:"Ground Rescue", checklist:"Ground-side recovery and bunker support.", status:"Ready" },
  { name:"Vulture", group:"Industry", role:"Solo salvage", priority:"Solo Salvage", checklist:"Solo salvage loop and fast cleanup jobs.", status:"Favorite" },
  { name:"Zeus Mk II ES", group:"Exploration", role:"Expedition ship", priority:"Explorer", checklist:"Exploration, scouting, and future route planning.", status:"Active" }
];
